#!/usr/bin/env bash

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex='^((hotfix|bugfix|feature|refactor|style)/[a-zA-Z0-9\-]+)$'

message="Invalid branch name. Use one of: feature/, bugfix/, refactor/, hotfix/, style/. Example: feature/add-login-page"

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
  echo "\033[0;31m$message"
  exit 1
fi


