name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Ensure node_modules is ignored by Git
        uses: dkershner6/gitignore-parser@v1
        with:
          must_deny: 'node_modules'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -- --max-warnings 0

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Check commit messages
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^#].{10,72}'
          error: 'Commit message must be between 10 and 72 characters'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
